### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Mikahael** [animemoeus/BombSquad-Indonesia#1]
So I try to open the server, sir, and it just defaults to regular bs. Your new powerup does not seem to be enabled for some reason. Why does it not work, sir? If it does work, how do I enable it, sir?

**Comment by animemoeus** [comment]
All features are enabled by default.

![Screenshot (81)](https://user-images.githubusercontent.com/33395829/109393932-5e8bb400-795f-11eb-8b6a-e6e0de61e834.png)

![Screenshot (82)](https://user-images.githubusercontent.com/33395829/109393883-28e6cb00-795f-11eb-9ec1-36dc1ebfae6c.png)

**Comment by animemoeus** [comment]
You can try to increase the random powerup

```dist/ba_data/python/ba/_powerup.py```

```
 ('shield', 2), ('health', 1), ('curse', 1),('random',1))
```
to
```
 ('shield', 2), ('health', 1), ('curse', 1),('random',100))
```
